name: DevSecOps for a Polygot Application
on:
  push:                                       
    branches:                              
      - main

jobs:
  docker-lint:
    name: LintChecking-Docker-Hadolint
    runs-on: ubuntu-latest
    # needs: secret-scanning
    steps:
      - uses: actions/checkout@v3

      - name: Run Hadolint
        run: docker run --rm -i hadolint/hadolint < Dockerfile | tee hadolint-result.txt
        continue-on-error: true
      
      - name: Upload the artifacts
        uses: actions/upload-artifact@v3.1.1
        with:
          name: hadolint-result
          path: hadolint-result.txt
