name: DevSecOps for a Polygot Application
on:
  push:                                       
    branches:                              
      - main

jobs:
  secret-scanning:
    name: SecretScanning-Python-Truffle Hog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3'

      - run: |
          pip3 install --upgrade virtualenv
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt

      - name: Run Truffle Hog
        run: docker run --rm -v $(pwd):/src hysnsec/trufflehog --json --regex --entropy=False file:///src > trufflehog-results.json
        continue-on-error: true
      
      - name: Upload the Output as an artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Truffle Hog Output
          path: trufflehog-results.json


  docker-lint:
    name: LintChecking-Docker-Hadolint
    runs-on: ubuntu-latest
    needs: secret-scanning
    steps:
      - uses: actions/checkout@v3

      - name: Run Hadolint
        run: docker run --rm -i hadolint/hadolint < Dockerfile
        continue-on-error: true

  component-analysis:
    name: ComponentAnalysis-Node-NPMAudit
    runs-on: ubuntu-latest
    needs: docker-lint
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v3

      - name: Install the Libraries or Node Modules
        run: npm install

      - name: Perform Node.js Audit and Output to Json file
        run: npm audit --json >> node-audit-results.json
        continue-on-error: true

      - name: List the files available
        run: ls
      
      - name: Upload the Output as an artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: NodeAudit Output
          path: node-audit-results.json
        if: always()


  build:
    name: Build-Job-Python
    runs-on: ubuntu-latest
    needs : docker-lint
    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3'
        continue-on-error: true

      - run: |
          pip3 install --upgrade virtualenv
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt
          python manage.py check
        continue-on-error: true

  test:
    name: FunctionalTesting-Job-Python
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3'

      - run: |
          pip3 install --upgrade virtualenv
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt
          python manage.py test taskManager

  oast-backend:
    name: SAST-Backend-Job-Python-Safety
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - run: docker run --rm -v $(pwd):/src hysnsec/safety check -r requirements.txt --json | tee oast-results.json
        continue-on-error: true             # allow the build to fail, similar to "allow_failure: true" in GitLab

      - uses: actions/upload-artifact@v3.1.1
        with:
          name: Safety
          path: oast-results.json
        if: always()                        # what is this for?

  oast-frontend:
    name: SAST-Frontend-Job-NodeJS-RetireJS
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: '10.x'

      - run: npm install

      - run: docker run --rm -v $(pwd):/src -w /src hysnsec/retire --outputformat json --outputpath retirejs-report.json --severity high
        continue-on-error: true

      - uses: actions/upload-artifact@v3.1.1
        with:
          name: RetireJS
          path: retirejs-report.json
        if: always()                        # what is this for?

  oast-snyk:
    name: SecretScanning-NodeJS-Synk
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@master      
      - uses: snyk/actions/setup@master
      - uses: actions/setup-go@v1
        with:
          go-version: "1.13"

      - uses: actions/setup-node@v3.5.1
        with:
          node-version: '10.x'

      - name: Install Node modules
        run: npm install

      - name: Run Snyk
        run: snyk test --json > snyk-results.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      - uses: actions/upload-artifact@v3.1.1
        with:
          name: Snyk               
          path: snyk-results.json
        if: always()


  oast-backend-bandit:
    name: Bandit Scan
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Run Bandit
        run: docker run --rm -v $(pwd):/src hysnsec/bandit -r /src -f json > bandit-results.json
        continue-on-error: true

      - name: Upload the Output as an artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Bandit Output
          path: bandit-results.json