name: DevSecOps for a Polygot Application
on:
  push:                                       
    branches:                              
      - main

jobs:
  ossscan-run:
    name: OSS Audit - Python - OSS Index
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.6'

      - run: |
          pip3 install --upgrade virtualenv
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt

      - name: Run OSS Index
        run: docker run --rm -v $(pwd):/src hysnsec/ossindex -r /src -f json -o ossindex-results.json
        continue-on-error: true

      - name: Upload the Output as an artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: OSS Index Output
          path: ossindex-results.json