name: DevSecOps for a Polygot Application
on:
  push:                                       
    branches:                              
      - main

jobs:
  secret-scanning:
    name: SecretScanning-Python-Truffle Hog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Truffle Hog
        run: docker run --rm -v $(pwd):/src hysnsec/trufflehog --json --regex --entropy=False file:///src > trufflehog-results.json
        continue-on-error: true
      
      - name: Upload the Output as an artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Truffle Hog Output
          path: trufflehog-results.json