name: DevSecOps for a Polygot Application
on:
  push:                                       
    branches:                              
      - main

jobs:
  bandit-scan:
    name: Bandit Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Run Bandit
        run: docker run --rm -v $(pwd):/src hysnsec/bandit -r /src -f json -o bandit-results.json
        continue-on-error: true

      - name: Upload the Output as an artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Bandit Output
          path: bandit-results.json